#!groovy​
def branch = 'qa-upgrade-test'
//dataset, account
def noobaa_ip = '52.191.130.61'
def values = noobaa_ip.tokenize('.')
def dataset_size = '1024' // 10GB of dataset (changed to 1GB)
def aging_time = '10' // run for 5 hours (changed to 10 min)
//machinekiller
def start_killing_time = '30' // start killing after 30 minutes
def service = 'azure'
def resource = 'pipeline-dataset'
def zone = 'westus2'
def prefix = 'ubuntu-node-'
def min_machines = '0' // minimum 3 machine
def max_machines = '3' // maximum 10 machines
//cluster
def clusterResource = 'pipelie-cluster'
def clusterVnet = 'pipelie-cluster-vnet'
def clusterStorage = 'pipelieclusterdisks'
//agentMatrix
def azureName = 'agents-server'
def serverName = '52.183.81.85'
def agentsResource = 'pipeline-agents'
def agentsVnet = 'agents-vnet'
def agentsStorage = 'agentsserverstorage'
def serverImage = 'https://jenkinsnoobaastorage.blob.core.windows.net/vhd-images/NooBaa-1.0.0-demo.vhd'
//systemConfig
def nodeLocalIP = '10.0.0.21'
def serverLocalIP = '10.0.0.5'
def severExternalIP = '52.191.134.178'


node('jenkins-slave1-centos') {
   def buildResult = "SUCCESS"
   try {
    stage('Get code from GIT') {
        echo 'node name: jenkins-slave1-centos, ip: 13.66.228.207'
        echo 'Checkouting from git!'
        checkout([$class: 'GitSCM', branches: [[name: "*/${branch}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '7df4e257-eb85-4243-9dc3-568d6127f752', url: 'https://tamireran@github.com/noobaa/noobaa-core']]])
    }
    stage('Preparing environment') {
        echo 'copying the env file'
        sh script: """
                    yes | cp /usr/local/noobaa/.env $WORKSPACE/
                """
        echo 'Installing all needed npm packages!'
        // sh script: """
        //       export NVM_DIR=/usr/local/nvm
        //       . /opt/nvm/nvm.sh
        //       nvm install 6.11.2
        //       nvm alias default 6
        //       nvm use default
        //       cd $WORKSPACE
        //       npm install
        //       npm install azure cloud-cd
        // """
        // // npm install bluebird lodash winston setimmediate aws-sdk minimist azure dotenv googleapis request moment performance-now ws ip
        echo 'Deleting log file'
        sh script: """
                    cd $WORKSPACE/logs
                    rm -rf noobaa.log
                """
        }
    stage('Upgrading noobaa server') {
      echo 'NO UPGRADING!'
      sh script: """
    #           export NVM_DIR=/usr/local/nvm
    #           . /opt/nvm/nvm.sh            
              curl -u jackyalbo:711d9303458d34ad56c1a48716c02ee5e286570f -L $JENKINS_URL/job/mdserver/lastSuccessfulBuild/api/xml >/tmp/lastSuccessfulBuild.xml
              isMaster=\$(cat /tmp/lastSuccessfulBuild.xml | awk -F "<displayName>" '{print \$2}' | awk -F "</displayName>" '{print \$1}')
              if [[ "\${isMaster}" =~ "master" ]]
              then
                curl -u jackyalbo:711d9303458d34ad56c1a48716c02ee5e286570f -L $JENKINS_URL/job/mdserver/lastSuccessfulBuild/artifact/*zip*/archive.zip >/tmp/noobaa-NVA-latest.zip
    #             # cp -R /root/node_modules/noobaa-core/build $WORKSPACE
    #             # cp -R /root/node_modules/noobaa-core/node_modules $WORKSPACE/
                fname=\$(unzip -o /tmp/noobaa-NVA-latest.zip -d  /tmp/|grep "tar.gz"|awk '{ print \$2 }')
    #             node $WORKSPACE/src/test/system_tests/upgradeonly.js --upgrade_pack \$fname --target_ip $noobaa_ip  # dataset test
    #             node $WORKSPACE/src/deploy/azureSnapshots.js --resource $agentsResource --source $azureName --image $serverImage
    #             sleep 1m
    #             node $WORKSPACE/src/test/system_tests/upgradeonly.js --upgrade_pack \$fname --target_ip $serverName # agent_metrix test
    #             node $WORKSPACE/src/test/system_tests/upgradeonly.js --upgrade_pack \$fname --target_ip $serverLocalIP # system-configuration test
              else
                echo "not master"
              fi
           """
    }
    stage('Tests') {
      // Run the maven build
      parallel (
          "upgrades": {
            echo 'Doing some upgrade!'
            sh script: """
                export NVM_DIR=/usr/local/nvm
                . /opt/nvm/nvm.sh
                fname=\$(unzip -o /tmp/noobaa-NVA-latest.zip -d  /tmp/|grep "tar.gz"|awk '{ print \$2 }')
                node $WORKSPACE/src/test/qa/upgrade_test.js --upgrade_pack \$fname
            """
          }
      )
	}
	} catch (e) {
        buildResult = "FAILED"
        echo 'build failed with error ' + e
        throw e
            } finally {
                    def subject = "Job '${JOB_NAME}' (${BUILD_NUMBER}) version is " + buildResult
                    def appLog = readFile("${WORKSPACE}/logs/noobaa.log")
                    def details = "Please go to ${BUILD_URL} and verify the build. noobaa logs: " + appLog
                    mail subject: subject,
                        body: details,
                        to:  'yuliia.kovalenko@noobaa.com, liran.mauda@noobaa.com, nimrod.becker@noobaa.com'
            }
    }
